title: Owen Fitzgerald # your name (or website title) here
logo: "images/img.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/donbowen-lehigh/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/owenfitz/">GitHub</a>  
theme: jekyll-theme-minimal
